### PR TITLE
fix the tests and ensure the ips are fetched correctly

### LINKED ISSUE #15: Fix domain tests
Because of the time used by the api to set the domain's ip the tests fail sometimes because it wants to read them too soon

### PR DESCRIPTION
**Pull request by gaalexandre**
The ips are now fetched correctly.
A sleep was put in the destroy check to ensure that the api have time to destroy before it is checked.
Closes #15

### CODE REVIEW

File: mailgun/resource_mailgun_domain.go [hunk 1]
```diff
@@ -482,3 +480,26 @@ func ListCredentials(domain, apiKey string) ([]mailgun.Credential, error) {
...
+	if _, ok := d.GetOk("force_dkim_authority"); !ok {
+		d.Set("force_dkim_authority", false)
+	}
+	return []*schema.ResourceData{d}, nil
+}
+
+func getIps(ctx context.Context,mg *mailgun.MailgunImpl) ([]mailgun.IPAddress, error){
+	start := time.Now()
+	t := time.Now()
+	ipAddress, err :=mg.ListDomainIPS(ctx)
```
Comment (paulrbr-fl) [inline mailgun/resource_mailgun_domain.go]: can you add a space between `=` and `mg` please?

File: mailgun/resource_mailgun_domain_test.go [hunk 2]
```diff
@@ -185,7 +210,7 @@ func testAccDomainCheckDestroy(domain *fullDomain) resource.TestCheckFunc {
 		mg := testAccProvider.Meta().(*mailgun.MailgunImpl)
 		ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
 		defer cancel()
-
+		time.Sleep(5 * time.Second)
```
Comment (paulrbr-fl) [inline mailgun/resource_mailgun_domain_test.go]: does other terraform provider use hard coded `sleep`ing times like this?

**Review by paulrbr-fl — COMMENTED** [review]
I see there are commits from  #15, so I left two comments only on your new commit. 

Can you rebase your branch on top of `fretlink/master` to make sure you don't include commits from #15 please?

File: mailgun/resource_mailgun_domain.go (hunk 1 above)
Comment (gaalexandre) [reply mailgun/resource_mailgun_domain.go]: I'm doing it

File: mailgun/resource_mailgun_domain_test.go (hunk 2 above)
Comment (gaalexandre) [reply mailgun/resource_mailgun_domain_test.go]: I don't know i will check.

Comment (gaalexandre) [reply mailgun/resource_mailgun_domain_test.go]: I didn't found one in a test like that but i found one elsewhere.

File: mailgun/resource_mailgun_domain.go [hunk 3]
```diff
@@ -493,3 +491,15 @@ func ImportStatePassthroughDomain(d *schema.ResourceData, meta interface{}) ([]*
 	}
 	return []*schema.ResourceData{d}, nil
 }
+
+func getIps(ctx context.Context,mg *mailgun.MailgunImpl) ([]mailgun.IPAddress, error){
+	start := time.Now()
+	t := time.Now()
+	ipAddress, err := mg.ListDomainIPS(ctx)
+	for (err != nil && t.Sub(start)< 120 * time.Second) {
```
Comment (paulrbr-fl) [inline mailgun/resource_mailgun_domain.go]: What do you think about using the `retry` helper function provided by Terraform: https://github.com/hashicorp/terraform/blob/master/helper/resource/wait.go#L10?

There's an example usage here: https://github.com/terraform-providers/terraform-provider-vault/blob/d8921672d5e07aa78e4a6497478fafaa1b707537/vault/data_source_aws_access_credentials.go#L129-L169

Comment (gaalexandre) [reply mailgun/resource_mailgun_domain.go]: I will try.

**Review by paulrbr-fl — APPROVED** [review]
Thanks!
